<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE features [
  <!ELEMENT context (name,type,collected,trained,bagged)>
  <!ELEMENT expr (name,type,collected,trained,bagged)>
  <!ELEMENT var (name,type,collected,trained,bagged)>
  <!ELEMENT name      (#PCDATA)>
  <!ELEMENT type    (#PCDATA)>
  <!ELEMENT collected (#PCDATA)>
  <!ELEMENT trained    (#PCDATA)>
  <!ELEMENT bagged    (#PCDATA)>  
]>
<features>
<!-- CONTEXT FEATURES -->
	<context>
		<name>id</name>
		<type>int</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>line</name>
		<type>int</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>column</name>
		<type>int</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>filename</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>tdname</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>methodname</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>mtdmod</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>mtdln</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>	
	<context>
		<name>locnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>paranum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>fldnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>allloc</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>allloctp</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>locintnm</name><!-- all int num of allloc -->
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>locfltnm</name><!-- all int num of allloc -->
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>locarrnm</name><!-- all int num of allloc -->
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>allfld</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>allfldtp</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>inloop</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bodyctl</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>befsyn</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>bdsyn</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>afsyn</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>bes0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bes1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bes2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bes3</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bes4</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bes5</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bds0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bds1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bds2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>bds3</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>afs0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>afs1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>afs2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>afs3</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>lv0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>lv1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>lv2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>lv3</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</context>
	<context>
		<name>pstmt0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>pstmt1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>nstmt0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>nstmt1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>befcd</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>
	<context>
		<name>befpre</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</context>

<!-- VAR FEATURES -->
	<var>
		<name>varname</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</var>
	<var>
		<name>vartype</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>vnmlen</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>shortvn</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>vnmwds</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>ltt0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>ltt1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>ltt2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>wd0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>wd1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>wd2</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isint</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isflt</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isarr</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>iscoll</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>ispmtarr</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>prmtandspl</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>twdl0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>	
	<var>
		<name>lastassign</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<!-- <var>
		<name>dpvar0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>dpvar1</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var> -->
	<var>
		<name>dis0</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>dis0_l10</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>dis0_l20</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>dis0_g20</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>preassnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isparam</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isfld</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isfnl</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>isidxer</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>	
	<var>
		<name>bodyuse</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>outuse</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>incondnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>filecondnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>totcondnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>lastpre</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</var>
	
	<!--  
	<var>
		<name>varpre1st</name>	
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>varpre2nd</name>	
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>tppre1st</name>	
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>tppre2nd</name>	
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>tppre3rd</name>	
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	-->
	
	<var>
		<name>docexcp</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>docop</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>doczero</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	
	<var>
		<name>docone</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>docnon</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>docrange</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>docincode</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<!-- 
	<var>
		<name>argused</name>	pos & var combined feature
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var> -->
	<var>
		<name>tpfit</name>	<!-- pos & var combined feature -->
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>occpostime</name>		<!-- pos & var combined feature -->	
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	<var>
		<name>used</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</var>
	
<!-- PARTIAL EXPR FEATURES -->
	<expr>
		<name>pred</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>true</bagged>
	</expr>
	<expr>
		<name>posnum</name>
		<type>int</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>roottp</name>
		<type>str</type>
		<collected>true</collected>
		<trained>true</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>ariop</name>
		<type>str</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	
	<expr>
		<name>hight</name>
		<type>int</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>mtd0</name>
		<type>str</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>instcof</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>num0</name>
		<type>float</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>num1</name>
		<type>float</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
	<expr>
		<name>hasnull</name>
		<type>bool</type>
		<collected>true</collected>
		<trained>false</trained>
		<bagged>false</bagged>
	</expr>
</features>
